<?xml version="1.0" encoding="utf-8"?><Database Name="WEBSOFT" Class="AdminDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=WEBSOFT;User ID=sa" SettingsObjectName="DataContext.Properties.Settings" SettingsPropertyName="WEBSOFTConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.uspAdminGetAll" Method="uspAdminGetAll">
    <ElementType Name="uspAdminGetAllResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="YM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminInsert" Method="uspAdminInsert">
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="YM" Parameter="yM" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CreateDate" Parameter="createDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminGetInfoByAdminID" Method="uspAdminGetInfoByAdminID">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspAdminGetInfoByAdminIDResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="YM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminDeleteByAdminID" Method="uspAdminDeleteByAdminID">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminUpdateByAdminID" Method="uspAdminUpdateByAdminID">
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="YM" Parameter="yM" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CreateDate" Parameter="createDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspAdminGetInfoByAdminName" Method="uspAdminGetInfoByAdminName">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="uspAdminGetInfoByAdminNameResult">
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="YM" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspAdminCheckLogin" Method="uspAdminCheckLogin">
    <Parameter Name="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="return" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspFunctionGetAllByTree" Method="uspFunctionGetAllByTree">
    <Parameter Name="FunctionID" Parameter="functionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="AdminID" Parameter="adminID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspFunctionGetAllByTreeResult">
      <Column Name="FunctionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParrentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>